import asyncio
import json
import os
import re
from typing import Any

import ollama


class OllamaUnavailableError(RuntimeError):
    pass


class OllamaModelMissingError(RuntimeError):
    pass


class AnalysisParseError(RuntimeError):
    pass


_OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:3b")

_IDENTIFY_PROMPT = """\
You are an expert video content strategist. Read the full transcript below and identify the HOOK segment.

The hook is the portion where the creator grabs the viewer's attention, creates curiosity, or establishes the value proposition. It is NOT always at the very start — find where the real hook is regardless of position.

<transcript>
{full_text}
</transcript>

Before giving the JSON object, write out your step-by-step reasoning inside <think>...</think> tags. 
After the closing </think> tag, return ONLY a valid JSON object — no markdown, no explanation, nothing else:
{{
  "hook_text": "<exact text of the hook segment>",
  "hook_start_char": <integer: character index in full_text where hook begins>,
  "hook_end_char": <integer: character index in full_text where hook ends>,
  "hook_type": "<one of: Bold Claim | Question Hook | Story Hook | Problem-Solution | Shock Value | Social Proof | Curiosity Gap | Other>",
  "hook_duration_estimate": "<e.g. '20 seconds', '1.5 minutes'>",
  "rationale": "<one sentence explaining why this segment is the hook>"
}}"""

_CORRECT_TRANSCRIPT_PROMPT = """\
You are an expert language editor. Review the following transcript, which may have been automatically generated by speech-to-text software. 
It might contain grammar errors, missing punctuation, or incorrectly transcribed words.

Fix the grammar, spelling, and readability of the text. 
CRITICAL: Do NOT change the speaker's original meaning, do NOT translate the language (e.g. keep Urdu in Urdu script), and do NOT summarize. 
Return ONLY the corrected transcript text — no markdown, no explanation.

<transcript>
{full_text}
</transcript>"""

_SCORE_PROMPT = """\
You are an expert video content strategist scoring a hook segment.

Full transcript for context:
<transcript>
{full_text}
</transcript>

Identified hook ({hook_type}):
<hook>
{hook_text}
</hook>

Score this hook. Before giving the JSON object, write out your step-by-step reasoning inside <think>...</think> tags.
After the closing </think> tag, return ONLY a valid JSON object — no markdown, no explanation.
CRITICAL: For "key_teachings", you MUST extract exact, word-for-word substrings from the transcript in their original language. Do NOT translate or paraphrase.

{{
  "value_proposition": {{
    "score": <integer 1-10>,
    "explanation": "<what the viewer is promised and how clearly it is communicated>"
  }},
  "emotional_pull": {{
    "score": <integer 1-10>,
    "explanation": "<what emotion or urgency is triggered and how effectively>"
  }},
  "overall_score": <integer 1-10>,
  "strengths": ["<strength 1>", "<strength 2>"],
  "weaknesses": ["<weakness 1>", "<weakness 2>"],
  "improvement_suggestions": [
    "<specific, actionable suggestion 1>",
    "<specific, actionable suggestion 2>",
    "<specific, actionable suggestion 3>"
  ],
  "rewritten_hook_example": "<a rewritten version of the hook that applies the suggestions above>",
  "alternative_hooks": [
    "<Option 1: Bold Claim Hook> : <exact speaker transcript where the hook was extracted>",
    "<Option 2: Question Hook> : <exact speaker transcript where the hook was extracted>",
    "<Option 3: Story/Relatable Hook> : <exact speaker transcript where the hook was extracted>",
    "<Option 4: Curiosity Gap Hook> : <exact speaker transcript where the hook was extracted>",
    "<Option 5: Shock Value Hook> : <exact speaker transcript where the hook was extracted>"
  ],
  "key_teachings": [
    "<exact word-for-word excerpt 1 from the transcript in its ORIGINAL language (do not translate)>",
    "<exact word-for-word excerpt 2 from the transcript...>",
    "<exact word-for-word excerpt 3 from the transcript...>"
  ]
}}"""


def _get_client() -> ollama.Client:
    return ollama.Client(host=_OLLAMA_HOST)


def _call_ollama(prompt: str, format: str | None = None, on_chunk: Any | None = None, on_debug: Any | None = None) -> str:
    client = _get_client()
    try:
        kwargs = {
            "model": _MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "options": {"temperature": 0.2, "num_ctx": 8192},
        }
        if format:
            kwargs["format"] = format

        if on_chunk:
            kwargs["stream"] = True
            response_stream = client.chat(**kwargs)
            full_content = []
            for chunk in response_stream:
                content_chunk = chunk.message.content
                if content_chunk:
                    full_content.append(content_chunk)
                    on_chunk(content_chunk)
            raw_response = "".join(full_content)
            if on_debug:
                on_debug(prompt, raw_response)
            return raw_response
        else:
            response = client.chat(**kwargs)
            raw_response = response.message.content
            if on_debug:
                on_debug(prompt, raw_response)
            return raw_response
    except ollama.ResponseError as exc:
        msg = str(exc).lower()
        if "model" in msg and ("not found" in msg or "pull" in msg):
            raise OllamaModelMissingError(
                f"Model '{_MODEL}' is not installed in Ollama. "
                f"Run: 'ollama pull {_MODEL}' — then try again."
            ) from exc
        raise OllamaUnavailableError(
            "Local AI service returned an error. "
            f"Check that Ollama is running and model '{_MODEL}' is installed."
        ) from exc
    except (ConnectionError, ConnectionRefusedError, OSError) as exc:
        raise OllamaUnavailableError(
            "Local AI service is offline. "
            "Start it with: 'ollama serve' — then try again."
        ) from exc
    except Exception as exc:
        # Catch httpx/requests errors that Ollama SDK may raise
        exc_type = type(exc).__name__
        if "connect" in exc_type.lower() or "connect" in str(exc).lower():
            raise OllamaUnavailableError(
                "Cannot connect to Ollama. "
                "Start it with: 'ollama serve' — then try again."
            ) from exc
        raise OllamaUnavailableError(
            f"Unexpected error communicating with Ollama ({exc_type}). "
            "Ensure 'ollama serve' is running."
        ) from exc


def _extract_json(raw: str) -> dict:
    """Extract JSON from LLM response that may contain surrounding text or markdown."""
    # 1. Try direct parse first
    try:
        return json.loads(raw.strip())
    except json.JSONDecodeError:
        pass

    # 2. Split out the think block if properly closed
    if "</think>" in raw:
        cleaned = raw.split("</think>")[-1]
    else:
        cleaned = raw

    # 3. Strip markdown code fences
    cleaned = re.sub(r"```(?:json)?\s*", "", cleaned).strip().rstrip("`").strip()
    
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # 4. Iteratively search for a valid JSON object bounded by { and }
    end_idx = cleaned.rfind("}")
    if end_idx != -1:
        start_idx = cleaned.find("{")
        while start_idx != -1 and start_idx < end_idx:
            json_str = cleaned[start_idx:end_idx+1]
            try:
                return json.loads(json_str)
            except json.JSONDecodeError:
                start_idx = cleaned.find("{", start_idx + 1)

    print("--- OLLAMA JSON PARSE FAILURE RAW OUTPUT ---")
    print(raw)
    print("---------------------------------------------")
    raise AnalysisParseError(
        "Hook analysis returned an unexpected result. "
        "The content may be too short or lack clear structure to identify a hook."
    )


def _identify_hook_sync(full_text: str, on_chunk: Any | None = None, on_debug: Any | None = None) -> dict[str, Any]:
    prompt = _IDENTIFY_PROMPT.format(full_text=full_text)
    raw = _call_ollama(prompt, format=None, on_chunk=on_chunk, on_debug=on_debug)
    data = _extract_json(raw)

    # Validate and clamp character indices so they never exceed text length
    text_len = len(full_text)
    
    raw_start = data.get("hook_start_char")
    start_val = int(raw_start) if raw_start is not None else 0
    raw_end = data.get("hook_end_char")
    end_val = int(raw_end) if raw_end is not None else text_len
    
    start = max(0, min(start_val, text_len))
    end = max(start, min(end_val, text_len))

    return {
        "hook_text": data.get("hook_text", full_text[start:end]),
        "hook_start_char": start,
        "hook_end_char": end,
        "hook_type": data.get("hook_type", "Unknown"),
        "hook_duration_estimate": data.get("hook_duration_estimate", "unknown"),
        "rationale": data.get("rationale", ""),
    }


def _score_hook_sync(full_text: str, hook_text: str, hook_type: str, on_chunk: Any | None = None, on_debug: Any | None = None) -> dict[str, Any]:
    prompt = _SCORE_PROMPT.format(full_text=full_text, hook_text=hook_text, hook_type=hook_type)
    raw = _call_ollama(prompt, format=None, on_chunk=on_chunk, on_debug=on_debug)
    data = _extract_json(raw)

    def clamp(val: Any, lo: int = 1, hi: int = 10) -> int:
        try:
            return max(lo, min(hi, int(val)))
        except (TypeError, ValueError):
            return 5

    return {
        "value_proposition": {
            "score": clamp(data.get("value_proposition", {}).get("score")),
            "explanation": data.get("value_proposition", {}).get("explanation", ""),
        },
        "emotional_pull": {
            "score": clamp(data.get("emotional_pull", {}).get("score")),
            "explanation": data.get("emotional_pull", {}).get("explanation", ""),
        },
        "overall_score": clamp(data.get("overall_score")),
        "strengths": data.get("strengths", []),
        "weaknesses": data.get("weaknesses", []),
        "improvement_suggestions": data.get("improvement_suggestions", []),
        "rewritten_hook_example": data.get("rewritten_hook_example", ""),
        "alternative_hooks": data.get("alternative_hooks", []),
        "key_teachings": data.get("key_teachings", []),
    }


async def identify_hook(transcript_data: dict[str, Any], on_chunk: Any | None = None, on_debug: Any | None = None) -> dict[str, Any]:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _identify_hook_sync, transcript_data["full_text"], on_chunk, on_debug)


def _correct_transcript_sync(full_text: str, on_chunk: Any | None = None, on_debug: Any | None = None) -> str:
    prompt = _CORRECT_TRANSCRIPT_PROMPT.format(full_text=full_text)
    raw = _call_ollama(prompt, on_chunk=on_chunk, on_debug=on_debug)
    # Strip any markdown code fences if the model adds them
    cleaned = re.sub(r"```[^\n]*\n?", "", raw).strip().rstrip("`").strip()
    return cleaned if cleaned else full_text


async def correct_transcript(full_text: str, on_chunk: Any | None = None, on_debug: Any | None = None) -> str:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _correct_transcript_sync, full_text, on_chunk, on_debug)


async def score_hook(transcript_data: dict[str, Any], hook_identification: dict[str, Any], on_chunk: Any | None = None, on_debug: Any | None = None) -> dict[str, Any]:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(
        None,
        _score_hook_sync,
        transcript_data["full_text"],
        hook_identification["hook_text"],
        hook_identification["hook_type"],
        on_chunk,
        on_debug,
    )

